### ISSUE TITLE
Could the "Weather" default Tidbyt app be added here?

### ISSUE THREAD

**Issue by mtimkovich** [tidbyt/community#152]
I wanted to make some changes to it/fork it, but it doesn't seem to be included here (unless I missed it).

**Comment by rohansingh** [comment]
Update on this. We're definitely open to open sourcing built-in apps. The current blocker is we have to figure out the process for migrating these apps from the internal repo to the community repo without breaking existing installations.

**Comment by rarestg** [comment]
Piggybacking off this since I'm looking to produce movement similar to the stock Weather app :)
Where should we ask questions like "How do I freeze a Marquee and display a different screen after a specified delay?" ?
The Tidbyt section of stackoverflow doesn't seem to exist yet!

**Comment by btjones** [comment]
Also piggybacking on this - I'd love some more options on the google calendar app (which I'd be interested in forking/building). Some ideas:

- Allow users to customize the "no more meetings" message since not everyone uses their calendars exclusively for meetings
- Add a summary feature that shows a list of all events for the whole day, including all-day events. This could be nice to schedule for the morning so folks can see everything they have going on that day.
