### ISSUE TITLE
Plex Recently Added: How to use?

### ISSUE THREAD

**Issue by jiznon** [tidbyt/community#1968]
Hello, I'm not sure what i'm doing wrong to get this new app working on my tidbyt. What i've set in the tidbyt app for this app:

My Plex server is set to Preferred, not Required.
Server IP: the local IP of my plex server: 192.168.0.20
Server port: the local port of my plex server: 32400
Plex Token: my plex token per https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/
API Key: blank -- since i'm not using the nodejs route, this isn't used, right?

I save it but it never connects, just the cloud with the line through it in place of the preview.

I'm willing to try the nodeJS route if there were instructions. Any help would be greatly appreciated.

*EDIT: Apparently LAN connection isn't possible. Changed to public IP/port and it now works!

**Comment by noahpodgurski** [comment]
If you're running this from the tidbyt app, then the script is running on their servers, so your local IP of `192.168.0.20` won't work. You'll need to set `Secure Connections: Preferred` in your plex settings and use the local IP.

I write in the readme this is ill-advised since it is a bit of a security issue. The alternative is to run the nodejs server on the network and proxy the request through that with the API key.

**Comment by noahpodgurski** [comment]
Also, the instructions for setting up the proxy server are here https://github.com/tidbyt/community/tree/main/apps/plexrecentlyadded
