### ISSUE TITLE
FitbitWeight app gives OAuth error when authenticating

### ISSUE THREAD

**Issue by jwoglom** [tidbyt/community#2138]
Clicking "Connect" in the FitbitWeight app produces the following prompt:

> The app you're trying to connect did not provide valid information to Fitbit. Please report this issue to them.
> Developer information: invalid_request - Invalid redirect_uri parameter value

**Comment by rjison** [comment]
I abandoned this app because I ran into an issue where the Tidbyt folks said they would need to address an issue on their end with OAuth 2.0. 

Last time I checked they said it wasn't something they had planned to address. 

This was their note at the time:

I was actually completely unaware of this section in the spec:
The authorization server MAY issue a new refresh token, in which case the client MUST discard the old refresh token and replace it with the new refresh token.
- https://datatracker.ietf.org/doc/html/rfc6749#section-6
