### ISSUE TITLE
[Feature Request] "Game day only" option for IndyCar

### ISSUE THREAD

**Issue by cbrookins** [tidbyt/community#2286]
@jvivona 

Game day only option similar to Baseball/Football apps

**Comment by jvivona** [comment]
I'll consider it - doesn't seem like a useful feature to me personally  since the app is designed to give you info on the next race & not "today's race" - especially since there's no real time scoring updates (the data for that level in a usable format isn't free) .   For me - personally - knowing on a Sunday morning that a race is at 230PM on FOX - is way too late in my universe.

But I'll put it on my list of to-dos and consider it.
