### ISSUE TITLE
NJ Transit app gone missing?

### ISSUE THREAD

**Issue by jgluck** [tidbyt/community#2293]
Hello! It seems like the NJ Transit app has vanished from the list of apps available to load on the device. Any idea why?

**Comment by jgluck** [comment]
@Jason-J-Hunt any idea what could have happened here?

**Comment by jmanske** [comment]
The app has disappeared because the call to `get_schema` is failing. It is failing because `fetch_stations_from_website` is returning an empty array and there is this code in `get_schema`:
```python
    options = getStationListOptions()

    fields = [
        schema.Dropdown(
            id = "station",
            name = "Departing Station",
            desc = "The NJ Transit Station to get departure schedule for.",
            icon = "train",
            default = options[0].value,
            options = options,
        ),
    ]
```
calling schema function for nj_transit.star: Traceback (most recent call last):
  nj_transit.star:356:30: in get_schema
**Error: index 0 out of range: empty list**

It looks like however the author was trying to scrape the station list is not particularly stable because it does this:
```python
selector = html(nj_dv_page_response_body)
stations = selector.find(".vbt-autocomplete-list.list-unstyled.shadow.w-100.list-main").children_filtered(".scrollable-items").children()
```
Changes to the html on the page will make this fail to find the list of stations. I think that is what happened.
