### ISSUE TITLE
YahooFantasyNFL Doesn’t Recognize League ID

### ISSUE THREAD

**Issue by tlatkins** [tidbyt/community#2622]
I reinstalled the YahooFantasyNFL app for this season. After I successfully sign in and enter my League ID and add the app, I get the message, “ERROR! Please check your league ID.” I’m successfully connected to Yahoo! according to the app and my League ID is correct.
cc: @jweier

**Comment by jweier** [comment]
Hey - The app needs to be updated to reflect the 2024 season. I pinged the TidByt team about seeing if we could work together to improve the app and unfortunately I haven’t received a response. I’m a little hesitant to continue development on the app because the updating/debugging process is very challenging without being able to work with them or see the errors. 

I guess more to come…hopefully…

-Jay

**Comment by mbbruch** [comment]
I think the new GAME_KEY should be 449, though it sounds like there are bigger dev challenges with updating the app.
