### ISSUE TITLE
Today In History doesn't display anything

### ISSUE THREAD

**Issue by anthonygioeni** [tidbyt/community#2820]
This app displays the "cannot connect to cloud" looking icon, but doesn't display anything from the Wikipedia connection it is apparently supposed to be using. Screenshot is below.

![IMG_4171](https://github.com/user-attachments/assets/a5df19f9-8bfa-4990-b6d4-13c1502fbc59)

**Comment by jvivona** [comment]
@anthonygioeni - do you have any idea when the last time it worked?   I pulled the URL from the source code & tested it and wikipedia basically it only returning 1 thing in the feed - which is the definition of "birth, death, events" - which of course is useless - so I see why the app is coded the way it is.   I see a new api/url that works from wikipedia (that doesn't mean the old one has stopped working) - but it requires some changes to the code.

If it just started today - it's also possible wikipedia is having a bad day.  Let's wait another day and see if it's a "them" problem before we react.

maybe @amkimian has some input.  If not - I'm willing to take a look at it and see about moving it to the new url/api and getting a PR submitted for it.

**Comment by anthonygioeni** [comment]
I just got my tidbyt this weekend, so I have never seen this app work - I added it yesterday, and it was doing this from the start. Thanks for taking a look!

**Comment by anthonygioeni** [comment]
Also, I checked as suggested and it is still not working today, so does not appear Wikipedia was just "having a bad day".

**Comment by jvivona** [comment]
No worries - thanks for doing the legwork on it.  Let's wait a couple of days & see if @amkimian, who is the original author, weighs in.  If not, I'll see what I can do over the weekend to get it spruced up.

**Comment by anthonygioeni** [comment]
Sounds good, thank you!

**Comment by jvivona** [comment]
@anthonygioeni - just an update.  after looking at all the code & how the app was originally built to interpret a bunch of web page HTML instead of JSON data  - I determined I was going to need to gut about 90% of the existing app (and it would still be tied to the original author & we'd have to get input for any future changes).   So - I made a decision to just make a new app that uses the new feed / method from Wikipedia, etc.  Finishing it up today.  I made a late decision on Friday to support Spanish in the app as a display language option.  This version of the app shows 1 random event, 1 random birth & 1 random death each time it renders to the device - so the data is always changing throughout the day.

![this_day_history_en](https://github.com/user-attachments/assets/bb1d1ecb-21ac-43e2-be19-48405aacbaed)
![this_day_history_es](https://github.com/user-attachments/assets/537d414b-0ae9-4096-be56-5ff0376bddc2)

once it's published this will be called "This Day in Hist" in the app to add to devices.

```
id: this-day-history
name: This Day In Hist
summary: Historical events today
desc: Display 1 random historical event, 1 random person born and 1 random person who dies (if you select those options) today.  Uses Wikipedia information. / Muestra eventos históricos de hoy, incluyendo nacimientos y defunciones (si se selecciona). Usa información de Wikipedia.
author: jvivona
```

Just need some more tweaks and testing.

**Comment by jvivona** [comment]
here the PR in case you want to track it so you know when it's pushed into the community repo.  
#2829

**Comment by anthonygioeni** [comment]
Very cool! I will keep an eye out, thank you!

**Comment by jvivona** [comment]
@anthonygioeni - this got pushed today.   search for "historical" in the mobile app.   once you confirm, close the issue.

**Comment by anthonygioeni** [comment]
New app works great!
