### ISSUE TITLE
Sound Transit Applet:  Add Option to pin favorite bus routes

### ISSUE THREAD

**Issue by joshspicer** [tidbyt/community#924]
@bigfootjon - love the work you did with the sound transit applet. 

I'm looking to build an applet to display the departure schedule for my favorite bus routes, and thought i'd see if that's something you'd be willing to accept bundled into your applet?  Otherwise, i'll likely fork the work that you did here into a new applet.

Let me know!

**Comment by bigfootjon** [comment]
Sorry for the slow reply, holidays and so forth.

Based on your location tag on your profile I'm betting you mean buses for the Seattle region, if so yeah that's doable. 

I don't really have the time to update the code but I'm more in favor of expanding the existing applet rather than forking, if you're interested. I'm happy to do code-review but the changes should be relatively simple:

1. Update [the route type processing code](https://github.com/tidbyt/community/blob/main/apps/soundtransit/sound_transit.star#L196-L198) to allow bus routes (and change the `light_rail_routes` function name and probably clean it up a bit if you want)
2. Update [the agency lookup code](https://github.com/tidbyt/community/blob/main/apps/soundtransit/sound_transit.star#L186-L187) to add other operators (e.g. Metro). List can be found [here](https://api.pugetsound.onebusaway.org/api/where/agencies-with-coverage.xml?key=TEST)
3. Please fix [this line](https://github.com/tidbyt/community/blob/main/apps/soundtransit/sound_transit.star#L216) to be an `arrowUp` if you get a chance (lol)

NB: The "TEST" OBA API key should be good enough to test within the Seattle region, though I've noticed it occasionally has trouble if the origin IP is "outside" the Seattle area (I have no idea how this is figured out, but I ran into this a while ago when I was in Texas. I needed to VPN back into Seattle to work on the applet)
